development:
  adapter: postgresql
  database: xxxxxxxxxxxxxx
  host: localhost
  pool: 5
  username: xxxxxxxxxx
  password: xxxxxxxxxxxxxxxxxxx
  timeout: 5000
  encoding: utf8
  min_messages: warning

test:
  adapter: postgresql
  database: xxxxxxxxxxxxxx
  host: localhost
  pool: 5
  username: xxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxx
  timeout: 5000
  encoding: utf8
  min_messages: warning

production:
  adapter: sqlite3
  database: xxxxxxxxxxxxxxxxx
  pool: 5
  timeout: 5000
