development:
  adapter: postgresql
  database: radio_development
  host: localhost
  pool: 5
  username: radio
  password: com99123
  timeout: 5000
  encoding: utf8

test:
  adapter: postgresql
  database: radio_test
  pool: 5
  timeout: 5000
  username: radio
  password: com99123
  encoding: utf8
  host: localhost
  template: postgis

production:
  host: localhost
  adapter: postgresql
  database: radio_production
  pool: 5
  username: radio
  password: com99123
  timeout: 5000
  encoding: utf8
