development:
  adapter: postgresql
  database: radio_development
  host: localhost
  pool: 5
  username: radio
  password: f1r35t4rt3r
  timeout: 5000
  encoding: utf8
  min_messages: warning

test:
  adapter: postgresql
  database: radio_test
  host: localhost
  pool: 5
  username: radio
  password: f1r35t4rt3r
  timeout: 5000
  encoding: utf8
  min_messages: warning

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
